name: 🙋‍♂️ [FocusCursor] - 支持与反馈
description: "获取有关 FocusCursor、报告错误或请求功能的帮助。"
title: '🙋‍♂️ 支持与反馈: FocusCursor'
labels: ['support', 'feedback', 'question']
assignees:
  - jaywcjlove

body:
  - type: markdown
    attributes:
      value: |
        <img align="right" height="100" alt="FocusCursor" src="https://github.com/user-attachments/assets/53fd44d7-a20b-4202-a4ce-9b7512489dfe" /> 请尽可能详细地提供您的支持请求或反馈。

        这款工具能够清晰地突出显示光标的位置，让光标的移动和点击一目了然。它特别适用于会议、教学或视频教程制作等场合，帮助观众更轻松地跟随你的操作和思路，从而更好地吸引他们的注意力，提升信息的传递效果。

        ### 联系信息

        如果您在使用我们的应用时遇到任何问题或需要支持，请随时通过以下方式与我们联系：

        - **电子邮件支持**: [kennyiseeyou@gmail.com](mailto:kennyiseeyou@gmail.com)
        - **社交媒体**: [Twitter](https://twitter.com/jaywcjlove)

        我们会尽快回复您的消息，感谢您对我们应用的支持！


  - type: textarea
    attributes:
      label: 🙋‍♂️ 您需要什么帮助？
      description: 描述您面临的问题或您想要请求的功能。
      placeholder: 例如，我遇到了问题...
    validations:
      required: true

  - type: dropdown
    id: os_version
    attributes:
      label: "💻 桌面"
      description: 您的操作系统和版本。
      options:
        - macOS 15.0 (Sequoia)
        - macOS 14.0 (Sonoma)
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **如何向我发送应用程序的崩溃报告？**

        - 在 macOS 上打开 Finder
        - 从“前往”菜单中选择 **前往文件夹…** <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>G</kbd>
        - 输入：**~/Library/Logs/DiagnosticReports**
        - 在出现的列表中，选择所有以应用程序名称开头的文件，将它们压缩成 ZIP 文件并发送给我
        - 将文件附加到此问题中

  - type: textarea
    attributes:
      label: ℹ️ 补充说明
      description: 在此添加有关问题的其他上下文信息。
      placeholder: 例如：截图、复现步骤等。
    validations:
      required: false